package iprwc.util.MessageFactory;

public enum Message {
    LOGIN_FAILED,
    LOGIN_SUCCESS,
    ACCOUNT_CREATED,
    REGISTER_FAILED,
    INVALID_PASSWORD,
    FILES_UPLOADED,
    FILE_TYPE_NOT_ALLOWED,
    FILE_CANNOT_BE_SAVED,
    ALL_USERS_RETRIEVED,
    USER_FROM_ID_RETRIEVED,
    USER_PRIVILEGE_CHANGED,
    USER_PRIVILEGE_RETRIEVED,
    USER_NOT_PRIVILEGED,
    USER_LANGUAGE_CHANGED,
    USER_PASSWORD_CHANGED,
    ALL_PROFILES_GOTTEN,
    PASSWORD_NOT_NEW,
    USER_DELETED,
    ALL_PRODUCTS_RETRIEVED,
    ALL_PRODUCTS_RETRIEVED_FAILED,
    PRODUCT_RETRIEVED,
    PRODUCT_DELETED,
    PRODUCT_ADDED,
    DUPLICATE_PRODUCT
}

